### PR TITLE
fix school_course_status to pull correct school years for cross join

### PR DESCRIPTION
**Pull request by bakerfranke**

### CODE REVIEW

**Comment by bakerfranke** [comment]
When Jan 1, 2023 hit, it exposed some incorrect date logic in this code.  
The code attempts to set up a "template" of sorts as a cross-join between every possible school_year and course_name pairing.  So if there are 8 total school years and 6 possible courses, it would mean that every school will have 8x6 = 48 records in this table to show the school's course status for each course for each year.

The cross-join (see the commit) uses analysis.school_years to figure out all the relevant school years, which in theory are 2013-14 up to the current school year, whatever that is.  Since school_years is pre-populated up to 2030, there is a risk that bad logic could introduce incorrect school years into the cross-join, which is what happened here.

In the end, the fix simply meant moving a `-1` to the other side of an inequality that is attempting to flag school years with TRUE or FALSE to be included in the cross-join.  The plain-english logic should be: "If the school_year is before the current date, or the current date is within the current school_year, mark that school_year as TRUE, otherwise, FALSE"

The current code checks whether the current month is > 6 (after june) and extracts the appropriate year from the systemdate, since e.g. the 2022-23 school year starts after june, the year needs to be 2022 between june-Dec, and 2023 after Jan. 1

An alternative approach would be to use a logical statement like this:
`sysdate > sy.start_date OR sysdate BETWEEN started_at and ended_at`

But this was not included in this PR.  Just made a small change to the existing code.

**Comment by angelakwon-code** [comment]
Walked through the logic myself; this looks good to me!

**Review by angelakwon-code — APPROVED** [review]

**Comment by angelakwon-code** [comment]
You can go ahead and merge the PR @bakerfranke!

**Comment by angelakwon-code** [comment]
Guessing this got lost in your inbox, so I'll go ahead and merge.

**Pull request merged**
